### ISSUE TITLE
Complete, clarify, and fix the format documentation

### ISSUE THREAD

**Issue by scriptin** [KanjiVG/kanjivg.github.com#2]
- :warning: Misleading info about `part` and `number`. It says that `part` is redundant, but if you look at [茲/08332.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/08332.svg), you can clearly see that `number` enumerates different components, while `part` enumerates parts of a same component which is split by another interleaving component.
- Description of the `number` attribute is not complete. The meaning is described completely, but it ends abruptly with `For instance,`. I think that [example](https://github.com/KanjiVG/kanjivg/blob/master/kanji/08332.svg) above would be nice to see here.
- Descriptions of `phon`, `tradForm`, `radicalForm` are missing completely
- No description of a general file layout. For example:
  - There are two main groups: strokes and numbers
  - Strokes root group contains a tree of components, ...
  - Numbers are positioned near their corresponding strokes, at their starting points
  - etc.
- No description of standard attributes: why are they there, what is allowed and what is not, etc.

**Comment by scriptin** [comment]
BTW, I can do this myself, but at least I need someone to confirm my statements above, as well as information about `phon`, `tradForm`, `radicalForm` attributes.

**Comment by benkasminbullock** [comment]
> * ⚠️ Misleading info about `part` and `number`. It says that `part` is redundant, but if you look at [茲/08332.svg](https://github.com/KanjiVG/kanjivg/blob/master/kanji/08332.svg), you can clearly see that `number` enumerates different components, while `part` enumerates parts of a same component which is split by another interleaving component.

That seems to be just an error in that file.

https://github.com/KanjiVG/kanjivg/tree/fix08332

> * Description of the `number` attribute is not complete. The meaning is described completely, but it ends abruptly with `For instance,`. I think that [example](https://github.com/KanjiVG/kanjivg/blob/master/kanji/08332.svg) above would be nice to see here.

I don't think that's a good example, since it's clearly in error. I've removed the "For instance" text.

https://github.com/KanjiVG/kanjivg.github.com/commit/da358b26b2be77a971c9fd65f3bba5a72b433726

> * Descriptions of `phon`, `tradForm`, `radicalForm` are missing completely
> * No description of a general file layout. For example:

I've copied and pasted the text which Ulrich Apel sent to the KanjiVG mailing list about the first of these. No information about radicalForm seems to exist in the mailing list archive so that will have to stay blank for now.
   
https://github.com/KanjiVG/kanjivg.github.com/commit/83cd5cf5797c889313382f0e0edb311341ad451b

>   * There are two main groups: strokes and numbers
>   * Strokes root group contains a tree of components, ...
>   * Numbers are positioned near their corresponding strokes, at their starting points
>   * etc.
> * No description of standard attributes: why are they there, what is allowed and what is not, etc.

Most of this is already documented. I've added some text as you suggest in the uppermost commit.

I'll close this issue now, but feel free to reopen if not satisfied.
