### ISSUE TITLE
Cluttered Root Folder

### ISSUE THREAD

**Issue by ElectronicsArchiver** [KanjiVG/kanjivg.github.com#7]
I would highly recommend to move all website content related files into either:
- A `docs` subfolder ( GitHub sadly requires it to be called `docs` )
- Or a dedicated branch

This would tidy up the repository immensely
and shouldn't bring any real downsides with it.

**Comment by benkasminbullock** [comment]
This repository contains only the website documentation, the repository for the kanjivg information itself is in https://github.com/KanjiVG/kanjivg.

**Comment by benkasminbullock** [comment]
I don't think moving a documentation-only repository to a "docs" subdirectory makes sense so I'll just close this.

**Comment by ElectronicsArchiver** [comment]
`docs` does not refer to `documentation` but its GitHubs only 
allowed name for GitHub pages folders and refers to `documents.

**Comment by benkasminbullock** [comment]
There is a sum total of twenty-six files in the top directory, so it's hardly "cluttered". 

The solution you suggest is to "move all website content related files" into docs, or put them on a separate branch. After your suggested action, there would be exactly the same number of files in either the docs directory, or in the separate branch, since this repository only contains the website files. 

What "docs" refers to or abbreviates seems to not be relevant to the discussion, so I'm not sure whether you're being serious at this point.

**Comment by ElectronicsArchiver** [comment]
- There are `25` items in root

- `26` / `25` files is clutter,
  having to scroll down multiple
  times just to see the README
  shows that.

  Considering that most of the items
  are direct content files - html -
  it would only be natural to not want
  them to be in the root folder of a
  project.

- There are not the same number of 
  GitHub Pages related files in root.

   ### Unrelated File Examples
   - README
   - gitignore
   - gitmodules

- The folder name `docs` is relevant, as it is the only 
  valid name for a GitHub Pages folder that can be used.

**Comment by ElectronicsArchiver** [comment]
Here is an **[Example]**.

*Of course in proper fashion I wouldn't move the*
*html chechking tool into the docs folder but into*
*a `Tools` or `Source` folder.*

*Would have to adjust it for that ofc though.*

[Example]: https://github.com/ElectronicsArchiver/kanjivg.github.com

**Comment by benkasminbullock** [comment]
I don't have anything to add beyond what I said above.
